dynamodb:
  image: amazon/dynamodb-local

app:
  build: .
  volumes:
    - .:/build
  environment:
    DYNAMODB_ENDPOINT: http://dynamodb:8000
    AWS_ACCESS_KEY_ID: aws_access_key_id
    AWS_SECRET_ACCESS_KEY: aws_secret_access_key
  command: sbt run
  ports:
    - "9000:9000"
  links:
    - dynamodb
  stdin_open: true
